### ISSUE TITLE
Invalid owner ID when deleting super table field

### ISSUE THREAD

**Issue by bartdigitalpulse** [ostark/upper#62]
At first I thought this was an issue with the super table field plugin but when I disable the Upper plugin I no longer have this issue. 
Attached the stack trace. 

Craft edition & version | Craft Pro 3.7.36
Upper | 1.9.1
Super Table | 2.7.1

PHP version | 7.4.27

```
yii\base\InvalidConfigException: Invalid owner ID: 26 in /home/vagrant/code/webiste/vendor/verbb/super-table/src/elements/SuperTableBlockElement.php:311
Stack trace:
#0 /home/vagrant/code/webiste/vendor/craftcms/cms/src/helpers/ElementHelper.php(413): verbb\supertable\elements\SuperTableBlockElement->getOwner()
#1 /home/vagrant/code/webiste/vendor/craftcms/cms/src/helpers/ElementHelper.php(413): craft\helpers\ElementHelper::rootElement()
#2 /home/vagrant/code/webiste/vendor/craftcms/cms/src/helpers/ElementHelper.php(413): craft\helpers\ElementHelper::rootElement()
#3 /home/vagrant/code/webiste/vendor/craftcms/cms/src/helpers/ElementHelper.php(451): craft\helpers\ElementHelper::rootElement()
#4 /home/vagrant/code/webiste/vendor/ostark/upper/src/EventRegistrar.php(224): craft\helpers\ElementHelper::isDraftOrRevision()
#5 /home/vagrant/code/webiste/vendor/ostark/upper/src/EventRegistrar.php(41): ostark\upper\EventRegistrar::handleUpdateEvent()
#6 [internal function]: ostark\upper\EventRegistrar::ostark\upper\{closure}()
#7 /home/vagrant/code/webiste/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#8 /home/vagrant/code/webiste/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#9 /home/vagrant/code/webiste/vendor/craftcms/cms/src/services/Elements.php(1722): yii\base\Component->trigger()
#10 /home/vagrant/code/webiste/vendor/verbb/super-table/src/fields/SuperTableField.php(1110): craft\services\Elements->deleteElement()
#11 /home/vagrant/code/webiste/vendor/craftcms/cms/src/base/Element.php(4178): verbb\supertable\fields\SuperTableField->beforeElementDelete()
#12 /home/vagrant/code/webiste/vendor/craftcms/cms/src/elements/MatrixBlock.php(454): craft\base\Element->beforeDelete()
#13 /home/vagrant/code/webiste/vendor/craftcms/cms/src/services/Elements.php(1672): craft\elements\MatrixBlock->beforeDelete()
#14 /home/vagrant/code/webiste/vendor/craftcms/cms/src/fields/Matrix.php(1075): craft\services\Elements->deleteElement()
#15 /home/vagrant/code/webiste/vendor/craftcms/cms/src/base/Element.php(4178): craft\fields\Matrix->beforeElementDelete()
#16 /home/vagrant/code/webiste/vendor/verbb/super-table/src/elements/SuperTableBlockElement.php(399): craft\base\Element->beforeDelete()
#17 /home/vagrant/code/webiste/vendor/craftcms/cms/src/services/Elements.php(1672): verbb\supertable\elements\SuperTableBlockElement->beforeDelete()
#18 /home/vagrant/code/webiste/vendor/verbb/super-table/src/fields/SuperTableField.php(1110): craft\services\Elements->deleteElement()
#19 /home/vagrant/code/webiste/vendor/craftcms/cms/src/base/Element.php(4178): verbb\supertable\fields\SuperTableField->beforeElementDelete()
#20 /home/vagrant/code/webiste/vendor/craftcms/cms/src/elements/MatrixBlock.php(454): craft\base\Element->beforeDelete()
#21 /home/vagrant/code/webiste/vendor/craftcms/cms/src/services/Elements.php(1672): craft\elements\MatrixBlock->beforeDelete()
#22 /home/vagrant/code/webiste/vendor/craftcms/cms/src/services/Matrix.php(1197): craft\services\Elements->deleteElement()
#23 /home/vagrant/code/webiste/vendor/craftcms/cms/src/services/Matrix.php(734): craft\services\Matrix->_deleteOtherBlocks()
#24 /home/vagrant/code/webiste/vendor/craftcms/cms/src/fields/Matrix.php(1036): craft\services\Matrix->saveField()
#25 /home/vagrant/code/webiste/vendor/craftcms/cms/src/base/Element.php(4160): craft\fields\Matrix->afterElementPropagate()
#26 /home/vagrant/code/webiste/vendor/craftcms/cms/src/services/Elements.php(2719): craft\base\Element->afterPropagate()
#27 /home/vagrant/code/webiste/vendor/craftcms/cms/src/services/Elements.php(784): craft\services\Elements->_saveElementInternal()
#28 /home/vagrant/code/webiste/vendor/craftcms/cms/src/controllers/GlobalsController.php(273): craft\services\Elements->saveElement()
#29 [internal function]: craft\controllers\GlobalsController->actionSaveContent()
#30 /home/vagrant/code/webiste/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#31 /home/vagrant/code/webiste/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#32 /home/vagrant/code/webiste/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#33 /home/vagrant/code/webiste/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction()
#34 /home/vagrant/code/webiste/vendor/craftcms/cms/src/web/Application.php(602): craft\web\Application->runAction()
#35 /home/vagrant/code/webiste/vendor/craftcms/cms/src/web/Application.php(272): craft\web\Application->_processActionRequest()
#36 /home/vagrant/code/webiste/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#37 /home/vagrant/code/webiste/web/index.php(23): yii\base\Application->run()
#38 {main}
```

**Comment by ostark** [comment]
Can you replace the current version in your composer.json with "dev-fix/supertable" and run `composer u ostark/upper` to pull in this feature branch?

**Comment by bartdigitalpulse** [comment]
Allright, it works. I no longer get the error. Thanks!
